services:
  api1:
    build: .
    image: rinha-2026-rust-api:latest
    container_name: rinha-api1
    hostname: api1
    restart: always
    security_opt:
      - seccomp=unconfined
    logging:
      driver: "none"
    environment:
      - RINHA_INDEX_PATH=/data/specialist.bin
      - RINHA_SOCK_PATH=/tmp/sock/api1.sock
      - RINHA_EARLY_LIMIT=2500000
      - RINHA_EARLY_CANDIDATES=15000
    volumes:
      - sock-volume:/tmp/sock
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160M"
    networks:
      - rinha
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    image: rinha-2026-rust-api:latest
    container_name: rinha-api2
    hostname: api2
    restart: always
    network_mode: "none"
    security_opt:
      - seccomp=unconfined
    logging:
      driver: "none"
    depends_on:
      - api1
    environment:
      - RINHA_INDEX_PATH=/data/specialist.bin
      - RINHA_SOCK_PATH=/tmp/sock/api2.sock
      - RINHA_EARLY_LIMIT=2500000
      - RINHA_EARLY_CANDIDATES=15000
    volumes:
      - sock-volume:/tmp/sock
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160M"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  lb:
    image: rinha-2026-rust-api:latest
    container_name: rinha-lb
    hostname: lb
    restart: always
    security_opt:
      - seccomp=unconfined
    logging:
      driver: "none"
    depends_on:
      - api1
      - api2
    entrypoint: ["/usr/local/bin/lb"]
    environment:
      - PORT=9999
      - FD_UPSTREAMS=/tmp/sock/api1.sock,/tmp/sock/api2.sock
      - WORKERS=2
    ports:
      - "9999:9999"
    volumes:
      - sock-volume:/tmp/sock
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30M"
    networks:
      - rinha
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  sock-volume:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=10m

networks:
  rinha:
    driver: bridge
